# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import lensapp.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0002_auto_20180322_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=lensapp.helpers.RandomFileName('photos/user-photos/')),
        ),
    ]
