# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0002_auto_20180322_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
