# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0003_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(default='images/none.png', upload_to='images/'),
        ),
    ]
