# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0004_auto_20180505_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(default='photos/user-photos/none.png', upload_to='photos/user-photos/'),
        ),
    ]
