# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import lensapp.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0005_auto_20180507_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=lensapp.helpers.RandomFileName('photos/user-photos/')),
        ),
    ]
