# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0008_remove_userprofile_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
