# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lensapp', '0003_auto_20180509_0757'),
        ('lensapp', '0009_userprofile_activated'),
    ]

    operations = [
    ]
